branches:
  only:
    - master
    - dev
notifications:
  email:
    - bp2013h1@lists.myhpi.de
language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6
install: 
  - pip install -r requirements.txt --use-mirrors
script:
  - python manage.py test
