branches:
  only:
    - master
    - dev
notifications:
  email:
    - ecocontrol@sec-i.org
language: python
python:
  - 2.7
env:
  - DJANGO_VERSION=1.6
addons:
  postgresql: "9.3"
install:
  - pip install -r requirements_travis.txt
  # Install conda
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes
  # Install some deps via conda
  - deps='pip numpy scipy dateutil'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip freeze
before_script:
  # Compile Holt Winters extension
  - export PROJECT_HOME="$(pwd)"
  - cd server/forecasting/statistical/  
  - python build_extension.py build_ext --inplace
  - cd $PROJECT_HOME
  # Set up database
  - psql -c "CREATE ROLE ecocontrol LOGIN PASSWORD 'sec-i' SUPERUSER CREATEDB CREATEROLE;" -U postgres
  - createdb ecocontrol
  - python manage.py syncdb --noinput
script:
  - coverage run --source='.' manage.py test
after_success:
  - coverage report
  - coveralls