# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.7"
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.6
# Tell it the things it will need to install when it boots
install: 
   # Install whatever version of Django that's listed above
   # Travis is currently working on
  - pip install pytz
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install south
script:
  - cd server
  - python manage.py test
  - cd ../sensor_mocking
  - python test.py