branches:
  only:
    - master
    - dev
    - dev-postgres
notifications:
  email:
    - bp2013h1@lists.myhpi.de
language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6
install: 
  - pip install -r requirements.txt --use-mirrors
before_script:
  - psql -U postgres -c 'create database bp2013h1;' -U postgres
script:
  - coverage run --source='.' manage.py test
  - coverage report
