branches:
  only:
    - master
    - dev
notifications:
  email:
    - ecocontrol@sec-i.org
language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6
addons:
  postgresql: "9.3"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-dateutil python-numpy python-psycopg2 python-scipy python-dev
 - easy_install Cython
install: 
  - pip install -r requirements_travis.txt
  - cd server/forecasting/statistical/  
  - python build_extension.py build_ext --inplace
  - cd ../../../
before_script:
  - psql -c "CREATE ROLE ecocontrol LOGIN PASSWORD 'sec-i' SUPERUSER CREATEDB CREATEROLE;" -U postgres
  - createdb ecocontrol
  - python manage.py syncdb --noinput
script:
  - coverage run --source='.' manage.py test
  - coverage report
after_success:
  - coverage report
  - coveralls