branches:
  only:
    - master
    - dev
notifications:
  email:
    - bp2013h1@lists.myhpi.de
language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-dateutil python-numpy python-psycopg2 python-scipy
install: 
  - pip install -r requirements_travis.txt --use-mirrors
# before_script:
#   - psql -U postgres -c 'create database bp2013h1;' -U postgres
script:
  - coverage run --source='.' manage.py test
  - coverage report
